[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
#base = ""

# Primary accent color for interactive elements.
primaryColor = "#60f0f8"

# Background color for the main content area.
backgroundColor = "#180048"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#100030"

# Color used for almost all text.
textColor = "#F0F8FF"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =

